### ISSUE TITLE
Are iframes supported by the Digital Credential API?

### ISSUE THREAD

**Issue by ryanhargrove** [WICG/digital-credentials#120] opened 2024-06-06 22:55 UTC
I was testing out the digital credential API from within an iframe and encountered this exception:

`
Failed to execute 'get' on 'CredentialsContainer': The digital identity credential can only be requested in a document which is same-origin with all of its ancestors.
`

Is there a config I need to set? Or is this generally not supported yet?

**Comment by timcappalli** [comment] 2024-06-06 22:57
Not currently, no. It is under consideration (#78)

**Comment by marcoscaceres** [comment] 2024-06-07 06:00
Closing as duplicate of #78.

**Closed by marcoscaceres** 2024-06-07 06:00 UTC
